version: "2"
services:
  http-server:
    extends:
      file: images/common.yml
      service: app
    command: python /app/server.py 8080

  extra-server:
    extends:
      file: images/common.yml
      service: app
    ports: [ "8080:8081" ]
    command: python /app/server.py 8080

  prometheus:
    extends:
      file: images/common.yml
      service: prometheus

  grafana:
    extends:
      file: images/common.yml
      service: grafana

networks:
  backend:
