apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
spec:
  limits:
  - default:
      memory: 1Gi
      cpu:    900m
    defaultRequest:
      memory: 0Mi
      cpu:    0
    type: Container
