apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
spec:
  limits:
  - default:
      memory: 500Mi
      cpu:    850m
    defaultRequest:
      memory: 50Mi
      cpu:    20m
    type: Container
